In [ ]:
#ASSIGNMENT 1: NumPy Array Explore

import numpy as np

#Create arrays
A = np.array([2,4,6,8,10,12,14,16,18,20])
B = np.zeros((3,3))
C = np.random.randint(1, 101, 5)
D = np.linspace(0, 5, 10)

print("Properties of Array A")
print("\nShape:", A.shape) #print shape
print("Data type:", A.dtype) #print data type
print("Size:", A.size) #print size
print("Dimensions:", A.ndim) #print dimensions
A_reshaped = A.reshape(2, 5) #Reshaping array A
print("Reshaped A (2x5):", A_reshaped)
print("Max value:", A.max(), "Index:", A.argmax()) #Find max value and index
print("Min value:", A.min(), "Index:", A.argmin()) #find min value and index
E = np.array([[1,2,3],[4,5,6],[7,8,9]]) #creat array E
print("\nElement at row 1 col 2:", E[1,2]) #print element at row1 and col2

Properties of Array A

Shape: (10,)
Data type: int64
Size: 10
Dimensions: 1
Reshaped A (2x5): [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max value: 20 Index: 9
Min value: 2 Index: 0

Element at row 1 col 2: 6


In [4]:
#ASSIGNMENT 2: NumPy Array Math Wizard

import numpy as np

# 1. Create arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
print("Addition:\n", arr1 + arr2) #addtition
print("Subtraction:\n", arr1 - arr2) #subtraction
print("Multiplication:\n", arr1 * arr2) #multiplication
print("Division:\n", arr1 / arr2) #division

# 4. Broadcasting explanation
# arr2 is a 1D array, NumPy automatically stretches it to match arr1 rows
# This allows element-wise operations without manually reshaping arr2

arr3 = np.array([1,4,9,16,25]) #creating array

print("\nSqrt:", np.sqrt(arr3)) #square root
print("Exp:", np.exp(arr3)) #exponenet
print("Sin:", np.sin(arr3)) #sin

arr4 = np.array([[5,12,3],[8,2,7]]) #creating array

print("\nSum of all elements:", np.sum(arr4)) #sum of all elements
print("Max of each column:", np.max(arr4, axis=0)) #max of each col
print("Min of each row:", np.min(arr4, axis=1)) #max of each row

arr1_float = arr1.astype(float) #converting into float
print("\nFloat version of arr1:\n", arr1_float)

Addition:
 [[11 22 33]
 [14 25 36]]
Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]
Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]
Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]

Sqrt: [1. 2. 3. 4. 5.]
Exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

Sum of all elements: 37
Max of each column: [ 8 12  7]
Min of each row: [3 2]

Float version of arr1:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
#ASSIGNMENT 3: Pandas DataFrame Detective
import pandas as pd
import numpy as np

# Create dictionary
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
    'Age': [25,30,np.nan,35,28,np.nan],
    'Score': [85,92,78,np.nan,88,95],
    'Grade': ['A','A','B','C','B','A']
}
df = pd.DataFrame(data) #Create DataFrame
print(df)
print("Head:", df.head(3)) #head
print("Shape:", df.shape) #shape
print("Columns:", df.columns) #cols
print("Data types:", df.dtypes) #dtype

print("Missing values:", df.isnull()) #check for null data

df['Age'] = df['Age'].fillna(df['Age'].mean()) #fill age with mean
df = df.dropna(subset=['Score']) #drop rows with missing score

print("After handling missing data:", df)

print("Name & Score:", df[['Name','Score']]) #Selection name and score
print("Score > 85:", df[df['Score'] > 85]) #select rows with score higher than 85

df_indexed = df.set_index('Name') #setting name as index
print("Indexed DataFrame:", df_indexed)

print("Unique Grades:", df['Grade'].unique()) #unique grades
print("Grade Counts:", df['Grade'].value_counts()) #grade count
print("Sorted by Score:", df.sort_values(by='Score', ascending=False)) #sort by score descending 


      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A
Head:       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
Shape: (6, 4)
Columns: Index(['Name', 'Age', 'Score', 'Grade'], dtype='str')
Data types: Name         str
Age      float64
Score    float64
Grade        str
dtype: object
Missing values:     Name    Age  Score  Grade
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False   True  False
4  False  False  False  False
5  False   True  False  False
After handling missing data:       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A
Name & Score:       Name  Score
0    Alice   85.0
1      B

In [15]:
a=[1,2,3]
b=2
a*b 
[1,2,3] + [4,5,6] 
np.exp([0,1,2]) 
[1,2,3] > 2

TypeError: '>' not supported between instances of 'list' and 'int'